---
- hosts: all
  tasks:
  - name: add openjdk repo to enable download of openjdk-8
    apt_repository:
      repo=ppa:openjdk-r/ppa
      state=present
  - name: install zsh, git, curl, openjdk-8, maven, vim, mysql-server, python-mysqldb
    apt:
      name={{ item }}
      update_cache=yes
    with_items:
      - zsh
      - git
      - openjdk-8-jdk
      - maven
      - vim
      - mysql-server
      - python-mysqldb
  - name: Clone oh-my-zsh repo
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/$user/.oh-my-zsh
  - name: Set zsh as default shell
    user: name=$user shell=/bin/zsh
  - name: download IntelliJ from centerdevice
    get_url: url=https://public.centerdevice.de/download/8adbcadf-a6e1-4fce-b2a3-f4748cb5d234.8a1681b0-578b-46d1-8efd-8a35fbb6db80 dest=/opt/intellij.tar.gz validate_certs=no
  - name: download Eclipse from centerdevice
    get_url: url=https://public.centerdevice.de/download/51c5bc60-8cd5-484b-bf08-ba07345661f5.4665a281-3da0-4cdd-b618-2c9db6ca3b9f dest=/opt/eclipse.tar.gz validate_certs=no
  - name: create directory for IntelliJ and Eclipse
    file: path={{ item }} state=directory
    with_items:
      - /opt/IntelliJ
      - /opt/Eclipse
  - name: unpack IntelliJ
    unarchive:
      src=/opt/intellij.tar.gz
      dest=/opt/IntelliJ
  - name: unpack Eclipse
    unarchive:
      src=/opt/eclipse.tar.gz
      dest=/opt/Eclipse
  - name: set global path to java 8 in /etc/profile
    lineinfile:
      dest=/etc/profile
      line="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      state=present"
  - name: create Desktop files for IntelliJ and Eclipse
    template:
      src=files/{{ item }}.desktop
      dest=/home/vagrant/Desktop owner=vagrant
    with_items:
      - sts
      - jetbrains-idea-ce
  - name: create IntelliJ folder
    file:
      path=/home/vagrant/IdeaProjects
      state=directory
      mode=0755
      owner=vagrant
  - name: create empty Worblehat database
    mysql_db:
      name=worblehat
      state=present
  - name: create Worblehat database user
    mysql_user:
      name=worblehat
      password=worblehat
      state=present
      priv=worblehat.*:ALL
