--- 
- hosts: all 
  tasks:
  - name: add openjdk repo to enable download of openjdk-8
    apt_repository: repo=ppa:openjdk-r/ppa state=present
  - name: install zsh, git, curl, openjdk-8, maven 
    apt: name={{ item }} update_cache=yes
    with_items:
      - zsh
      - curl
      - git
      - openjdk-8-jdk
      - maven
  - name: make zsh default
    shell:  chsh -s /bin/zsh vagrant
  - name: install oh-my-zsh
    shell: sh -c '$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)'
  - name: download IntelliJ from centerdevice
    get_url: url=https://public.centerdevice.de/download/8adbcadf-a6e1-4fce-b2a3-f4748cb5d234.8a1681b0-578b-46d1-8efd-8a35fbb6db80 dest=/opt/intellij.tar.gz validate_certs=no
  - name: create directory for IntelliJ
    file: path=/opt/IntelliJ state=directory
  - name: unpack IntelliJ
    unarchive: src=/opt/intellij.tar.gz dest=/opt/IntelliJ